import React from 'react'

const HowAndWhyWeUseCookies = () => {
  return (
    <div>
       <h3>How and why we use cookies</h3>
                            <h5>Registered User</h5>
                            <p>When you visit <a href="https://www.SurePeople.com">www.SurePeople.com</a> and move from page to page, read pages, or download content onto your computer or device, we may collect certain information, including, without limitation, which pages are visited, what is downloaded, the domains our visitors came from (e.g. "facebook.com” or "google.com") and the addresses of sites visited immediately before coming to our site. SurePeople may also collect certain information through the use of "cookies." Cookies are bits of electronic information that a Website can transfer to a visitor's computer or device to help tailor and keep records of his or her visit to the Website.</p>
                            <p>Cookies help SurePeople improve the site's content by enhancing your overall experience on our Website. SurePeople does not store any personally identifiable information in these cookies. SurePeople uses Google Analytics, a web analytics service provided by Google, Inc. ("Google"). Google Analytics uses cookies to help us analyze how the Website is used. The information generated by the cookie about use of the Website (including your IP address) will be transmitted to and stored by Google on servers owned by Google.</p>
                            <p>Google may also transfer this information to third parties where required to do so by law, or where such third parties process the information on Google's behalf. The collected data is not tied to any single individual, no individual profiles are created, and Google will not associate your IP address with any other data held by Google. You may refuse the use of cookies by selecting the appropriate settings on your Web browser; however, please note that if you do this you may not be able to use the full functionality of this Website.</p>
                           
    </div>
  )
}

export default HowAndWhyWeUseCookies
